apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grupo1-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: grupo1
        image: alpine:3.14
